In [29]:
import numpy as np

In [30]:
# create array , matrix
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [31]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [32]:
#shape
print(a.shape , b.shape)

(4,) (2, 2)


In [33]:
#reshape
c = a.reshape([4,1])
c.shape

(4, 1)

In [39]:
d = a.reshape([2,-1,1])
d.shape

(2, 2, 1)

In [44]:
#concatenate
a = np.array([1,2,3])
b = np.array([4,5])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
d = a*b
print(c,d)

[5 7 9] [ 4 10 18]


In [53]:
e = np.array([10])
d= a + e
d

array([11, 12, 13])

In [56]:
e = a + 10
e

array([11, 12, 13])

In [57]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [59]:
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [62]:
b = a[2:7:2]
b

array([3, 5, 7])

In [63]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [64]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
sum_a = np.sum(a)
sum_a

np.int64(36)

In [66]:
max_a = np.max(a)
max_a

np.int64(8)

In [67]:
min_a = np.min(a)
min_a

np.int64(1)

In [68]:
a = np.array([4,2,9,6,7,3,5])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 9])

In [70]:
a = np.random.randint(-100,100,(3,4))
a

array([[  4, -16,  60, -96],
       [ -6,  57, -91,  94],
       [ 31, -11,  59, -33]], dtype=int32)

In [74]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
c.shape

(2, 3)

In [76]:
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [79]:
#normalize
mean_a = np.mean(a)
mean_a

np.float64(2.0)

In [80]:
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [82]:
norm_a = (a-mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [83]:
np.mean(norm_a)

np.float64(0.0)

In [84]:
np.std(norm_a)

np.float64(0.9999999999999999)